$set_environment_variables_back = <<SCRIPT
tee "/etc/profile.d/myvars.sh" > "/dev/null" <<EOF
# environment variables.
export DB_HOST=localhost
export DB_USER=applicationuser
export DB_PASS=applicationuser
export DB_NAME=movie_db
EOF
SCRIPT

$set_environment_variables_front = <<SCRIPT
tee "/etc/profile.d/myvars.sh" > "/dev/null" <<EOF
# environment variables.
export BACK_HOST=192.168.56.3
EOF
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.define "Api" do |cfg|
        cfg.vm.provider :virtualbox do |vb, override| 
          config.vm.box = "ubuntu/bionic64"
          override.vm.network "private_network", ip: "192.168.56.3"
          override.vm.hostname = "Api"
          vb.name = "Api"
          vb.cpus = 1
          vb.memory = 2048
          config.vm.provision :shell, inline: $set_environment_variables_back, :run => 'always'
          config.vm.provision "file", source:"../installation-scripts/basic_installations.sh", destination: "./basic_installations.sh"
          config.vm.provision "file", source:"../installation-scripts/back_installation.sh", destination: "./back_installations.sh"
          config.vm.provision "file", source:"../installation-scripts/mysql_install.sh", destination: "./mysql_install.sh"
          config.vm.provision "file", source:"../installation-scripts/create_schema_user.sql", destination: "./create_schema_user.sql"
        end
   end
   config.vm.define "Front" do |cfg|
        cfg.vm.provider :virtualbox do |vb, override| 
            config.vm.box = "ubuntu/bionic64"
            override.vm.network "private_network", ip: "192.168.56.2"
            override.vm.hostname = "Front"
            vb.name = "Front"
            vb.cpus = 1
            vb.memory = 1024
            config.vm.provision :shell, inline: $set_environment_variables_front, :run => 'always'
            config.vm.provision "file", source:"../installation-scripts/basic_installations.sh", destination: "./basic_installations.sh"
            config.vm.provision "file", source:"../installation-scripts/front_installation.sh", destination: "./front_installations.sh"
        end
    end
end