Vagrant.configure("2") do |config|
    config.vm.define "Api" do |cfg|
        cfg.vm.provider :virtualbox do |vb, override| 
          config.vm.box = "ubuntu/bionic64"
          override.vm.network "private_network", ip: "192.168.56.3"
          override.vm.hostname = "Api"
          vb.name = "Api"
          vb.cpus = 1
          vb.memory = 2048
          config.vm.provision "file", source:"~/Desktop/scripts/basic_installations.sh", destination: "./basic_installations.sh"
          config.vm.provision "file", source:"~/Desktop/scripts/back_installation.sh", destination: "./back_installations.sh"
          config.vm.provision "file", source:"~/Desktop/scripts/mysql_install.sh", destination: "./mysql_install.sh"
          config.vm.provision "file", source:"~/Desktop/scripts/create_schema_user.sql", destination: "./create_schema_user.sql"
        end
   end
   config.vm.define "Front" do |cfg|
        cfg.vm.provider :virtualbox do |vb, override| 
            config.vm.box = "ubuntu/bionic64"
            override.vm.network "private_network", ip: "192.168.56.2"
            override.vm.hostname = "Front"
            vb.name = "Front"
            vb.cpus = 1
            vb.memory = 1024
            config.vm.provision "file", source:"~/Desktop/scripts/basic_installations.sh", destination: "./basic_installations.sh"
            config.vm.provision "file", source:"~/Desktop/scripts/front_installation.sh", destination: "./front_installations.sh"
        end
    end
end